# Generated by Django 3.2.9 on 2021-12-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not to', 'Prefer Not to')], max_length=50)),
                ('number', models.CharField(blank=True, default='no number yet', max_length=50, null=True)),
                ('image', models.ImageField(default='default_avatar.png', upload_to='profile_pics/')),
                ('path', models.CharField(choices=[('AWS-DevOps', 'AWS-DevOps'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Custom', 'Custom')], max_length=50)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
