# Generated by Django 3.2.9 on 2021-12-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
